version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: emertat_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://emertat_backend:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: emertat_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/emertatdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: emertat_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
